"""
Django settings for WAM project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i(@t%n%skz1v)y-%b4+krov&l1efdc__m+oh!jn59%(!4n1r7+'

# I can't find a better way to do this in django!
WAM_URL = "http://localhost"
WAM_AUTO_EMAIL_FROM = "noreply@invalid.com"
WAM_ADMIN_CONTACT_EMAIL = "noreply@invalid.com"
WAM_ADMIN_CONTACT_NAME = "Help Desk"

# These regexs will be used for automatic creation of Staff objects when an authenticaed User is created
# They can be used to help WAM establish whether this should be a member of Academic Staff and External Examiner
# If these regexs are set, and an authenticated User is presented, login will be disabled
WAM_STAFF_REGEX = None
WAM_EXTERNAL_REGEX = None

# This is the activity type for module staff allocations
WAM_DEFAULT_ACTIVITY_TYPE = 1

# Whether to have ADFS authentication
# You will need other configuration changes, please see
# https://github.com/profcturner/WAM/wiki/ADFS---Azure-Authentication
WAM_ADFS_AUTH = False

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
DEBUG_TOOLBAR = False
ALLOWED_HOSTS = ["127.0.0.1"]

#ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admindocs',
    'django.contrib.humanize',
    'loads'
)

MIDDLEWARE = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.admindocs.middleware.XViewMiddleware',
)

ROOT_URLCONF = 'WAM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'loads.context_processors.staff'
            ],
        },
    },
]

WSGI_APPLICATION = 'WAM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# Where do we store media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

LOGOUT_REDIRECT_URL = 'logged out'

# New in Django 3.2, we should set an explicit automatic primary key type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Create a local settings file called local_settings.py to override details
try:
    from WAM.local_settings import *
except ImportError:
    pass