# Generated by Django 6.0 on 2025-12-09 22:17

import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# loads.migrations.0043_custom_ee2staff_20181115_2253

# But this should not be necessary, as it was to port things over from an object that was being destroyed
# It won't be created in a new install

class Migration(migrations.Migration):

    replaces = [('loads', '0001_initial'), ('loads', '0002_auto_20151017_1150'), ('loads', '0003_auto_20151017_1325'), ('loads', '0004_task_groups'), ('loads', '0005_auto_20151017_1334'), ('loads', '0006_courseworktracker_examtracker_loadtracking'), ('loads', '0007_auto_20151017_1422'), ('loads', '0008_auto_20151017_1958'), ('loads', '0009_auto_20151018_0817'), ('loads', '0010_auto_20151031_0058'), ('loads', '0011_auto_20151031_0106'), ('loads', '0012_auto_20151130_1311'), ('loads', '0013_auto_20151130_1540'), ('loads', '0014_auto_20151207_1909'), ('loads', '0015_auto_20151210_1225'), ('loads', '0016_workpackage'), ('loads', '0017_auto_20160610_2238'), ('loads', '0018_modulestaff_package'), ('loads', '0019_auto_20160612_1442'), ('loads', '0020_auto_20160612_1600'), ('loads', '0021_auto_20160612_1602'), ('loads', '0022_auto_20160612_1840'), ('loads', '0023_auto_20160615_0006'), ('loads', '0024_auto_20160627_1049'), ('loads', '0025_auto_20160627_1407'), ('loads', '0026_auto_20160629_1009'), ('loads', '0027_auto_20160701_1701'), ('loads', '0028_auto_20160706_2224'), ('loads', '0029_auto_20160726_1915'), ('loads', '0030_auto_20161004_2320'), ('loads', '0031_auto_20161007_2209'), ('loads', '0032_assessmentresource_owner'), ('loads', '0033_auto_20170724_1512'), ('loads', '0034_auto_20171005_1020'), ('loads', '0035_auto_20171018_1421'), ('loads', '0036_auto_20180213_1006'), ('loads', '0037_workpackage_hidden'), ('loads', '0038_assessmentstate_assessmentstatesignoff'), ('loads', '0039_auto_20180829_2202'), ('loads', '0040_workpackage_show_percentages'), ('loads', '0041_auto_20180915_2257'), ('loads', '0042_custom_ee2staff_20181115_2251'), ('loads', '0043_custom_ee2staff_20181115_2253'), ('loads', '0044_auto_20190313_1648')]

    initial = True

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('downloads', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.category')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('staff_number', models.CharField(max_length=20)),
                ('fte', models.PositiveSmallIntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'staff',
                'order_with_respect_to': 'user',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, default='')),
                ('details', models.TextField()),
                ('deadline', models.DateTimeField(help_text='This is a date and time in ISO format (YYYY-MM-DD HH:MM:SS)')),
                ('archive', models.BooleanField(default=False, help_text='Archived tasks will send no further notifications')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.category')),
                ('targets', models.ManyToManyField(blank=True, to='loads.staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='Hold down ctrl or cmd to select multiple groups', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.staff')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.task')),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'campuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10)),
                ('admin_scaling', models.FloatField()),
                ('assessment_scaling', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('draft', models.BooleanField(default=True)),
                ('archive', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('contact_admin_scaling', models.FloatField(default=1)),
                ('contact_assessment_scaling', models.FloatField(default=1)),
                ('credit_contact_scaling', models.FloatField(default=0.4)),
                ('nominal_hours', models.PositiveIntegerField(default=1600)),
                ('days_in_week', models.PositiveIntegerField(default=5)),
                ('working_days', models.PositiveIntegerField(default=228)),
                ('hidden', models.BooleanField(default=False)),
                ('show_percentages', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', '-startdate'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=10)),
                ('module_name', models.CharField(max_length=200)),
                ('semester', models.CommaSeparatedIntegerField(max_length=10)),
                ('campus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loads.campus')),
                ('admin_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assessment_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contact_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('credits', models.PositiveSmallIntegerField(default=20)),
                ('size', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loads.modulesize')),
                ('package', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loads.workpackage')),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['module_code'],
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.workpackage'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ModuleStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_proportion', models.PositiveSmallIntegerField()),
                ('admin_proportion', models.PositiveSmallIntegerField()),
                ('assessment_proportion', models.PositiveSmallIntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.module')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.staff')),
                ('package', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loads.workpackage')),
            ],
            options={
                'verbose_name_plural': 'module staff',
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('details', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'bodies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.activitytype')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.body')),
            ],
            options={
                'ordering': ['name', '-start'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('hours_per_week', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.project')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.staff')),
            ],
            options={
                'verbose_name_plural': 'project staff',
                'ordering': ['staff', '-start'],
            },
        ),
        migrations.CreateModel(
            name='ActivityGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('hours', models.PositiveSmallIntegerField()),
                ('percentage', models.PositiveSmallIntegerField()),
                ('hours_percentage', models.CharField(choices=[('H', 'Hours'), ('P', 'Percentage')], default='H', max_length=1)),
                ('semester', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
                ('details', models.TextField()),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.activitytype')),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loads.module')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.workpackage')),
                ('targets', models.ManyToManyField(blank=True, to='loads.staff')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('generator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loads.activitygenerator')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loads.project')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalExaminer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('staff_number', models.CharField(max_length=20)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.workpackage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_code', models.CharField(max_length=10)),
                ('programme_name', models.CharField(max_length=200)),
                ('deprecated_examiners', models.ManyToManyField(blank=True, to='loads.externalexaminer')),
                ('directors', models.ManyToManyField(blank=True, to='loads.staff')),
                ('package', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loads.workpackage')),
            ],
            options={
                'ordering': ['programme_name'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='lead_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_modules', to='loads.programme'),
        ),
        migrations.AddField(
            model_name='module',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_modules', to='loads.staff'),
        ),
        migrations.CreateModel(
            name='AssessmentResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('resource', models.FileField(upload_to='assessments/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('downloads', models.PositiveSmallIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.module')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.assessmentresourcetype')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loads.staff')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='programmes',
            field=models.ManyToManyField(blank=True, related_name='modules', to='loads.programme'),
        ),
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='module',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_modules', to='loads.staff'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='staff',
            order_with_respect_to=None,
        ),
        migrations.CreateModel(
            name='AssessmentStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.workpackage')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.staff')),
            ],
            options={
                'verbose_name_plural': 'assessment staff',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hours', models.PositiveSmallIntegerField()),
                ('percentage', models.PositiveSmallIntegerField()),
                ('hours_percentage', models.CharField(choices=[('H', 'Hours'), ('P', 'Percentage')], default='H', max_length=1)),
                ('semester', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.activitytype')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loads.module')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.staff')),
                ('package', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loads.workpackage')),
                ('activity_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loads.activityset')),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.AlterField(
            model_name='module',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_modules', to='loads.staff'),
        ),
        migrations.CreateModel(
            name='AssessmentState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('actors', models.TextField()),
                ('notify', models.TextField()),
                ('initial_state', models.BooleanField(default=False)),
                ('next_states', models.ManyToManyField(blank=True, related_name='children', to='loads.assessmentstate')),
                ('priority', models.IntegerField(default=10)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentStateSignOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notified', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('assessment_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.assessmentstate')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.module')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='has_workload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='targets',
            field=models.ManyToManyField(blank=True, help_text='Hold down ctrl or cmd to select multiple users', to='loads.staff'),
        ),
        migrations.AddField(
            model_name='Programme',
            name='examiners',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_external': True}, null=True, to='loads.staff'),
        ),
        #migrations.RunPython(
        #    code=loads.migrations.0043_custom_ee2staff_20181115_2253.migrate_externals,
        #),
        migrations.RemoveField(
            model_name='Programme',
            name='deprecated_examiners',
        ),
        migrations.AlterField(
            model_name='activity',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_external': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.staff'),
        ),
        migrations.AlterField(
            model_name='assessmentstaff',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'is_external': False}, on_delete=django.db.models.deletion.CASCADE, to='loads.staff'),
        ),
        migrations.AlterField(
            model_name='module',
            name='coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_external': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_modules', to='loads.staff'),
        ),
        migrations.AlterField(
            model_name='module',
            name='moderators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_external': False}, related_name='moderated_modules', to='loads.staff'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='directors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_external': False}, related_name='directed_programmes', to='loads.staff'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='examiners',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_external': True}, related_name='examined_programmes', to='loads.staff'),
        ),
        migrations.AlterField(
            model_name='projectstaff',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'is_external': False}, on_delete=django.db.models.deletion.CASCADE, to='loads.staff'),
        ),
        migrations.AddField(
            model_name='assessmentstate',
            name='next_states_guidance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulestaff',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'has_workload': True}, on_delete=django.db.models.deletion.CASCADE, to='loads.staff'),
        ),
    ]
