# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0034_auto_20171005_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_modules', to='loads.Staff'),
        ),
        migrations.AlterField(
            model_name='module',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_modules', to='loads.Staff'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='staff',
            order_with_respect_to=None,
        ),
    ]
