# Generated by Django 2.0 on 2018-08-29 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loads', '0037_workpackage_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('actors', models.TextField()),
                ('notify', models.TextField()),
                ('initial_state', models.BooleanField(default=False)),
                ('next_states', models.ManyToManyField(blank=True, related_name='children', to='loads.AssessmentState')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentStateSignOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notified', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('assessment_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.AssessmentState')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.Module')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
