# Generated by Django 2.0 on 2018-08-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0038_assessmentstate_assessmentstatesignoff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentstate',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='assessmentstate',
            name='priority',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
