# Generated by Django 2.0 on 2018-09-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0039_auto_20180829_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='show_percentages',
            field=models.BooleanField(default=True),
        ),
    ]
