# Generated by Django 2.0 on 2018-09-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0040_workpackage_show_percentages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseworktracker',
            name='module',
        ),
        migrations.RemoveField(
            model_name='examtracker',
            name='module',
        ),
        migrations.DeleteModel(
            name='LoadTracking',
        ),
        migrations.DeleteModel(
            name='CourseworkTracker',
        ),
        migrations.DeleteModel(
            name='ExamTracker',
        ),
    ]
