# Generated by Django 2.1.1 on 2018-11-15 22:51

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0041_auto_20180915_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='has_workload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='semester',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='activitygenerator',
            name='semester',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archived tasks will send no further notifications'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(help_text='This is a date and time in ISO format (YYYY-MM-DD HH:MM:SS)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Hold down ctrl or cmd to select multiple groups', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='targets',
            field=models.ManyToManyField(blank=True, help_text='Hold down ctrl or cmd to select multiple users', to='loads.Staff'),
        ),
    ]
