# Generated by Django 2.1.1 on 2019-03-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0043_custom_ee2staff_20181115_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentstate',
            name='next_states_guidance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulestaff',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'has_workload': True}, on_delete=django.db.models.deletion.CASCADE, to='loads.Staff'),
        ),
    ]
