# Generated by Django 4.2.13 on 2025-10-18 21:45

from django.db import migrations, models
import django.db.models.deletion

from WAM.settings import WAM_DEFAULT_ACTIVITY_TYPE

class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0046_alter_modulesize_options_modulesize_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='abbreviation',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='colour',
            field=models.CharField(default='red', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulestaff',
            name='activity_type',
            field=models.ForeignKey(default=WAM_DEFAULT_ACTIVITY_TYPE, on_delete=django.db.models.deletion.CASCADE, to='loads.activitytype'),
        ),
    ]
