# Generated by Django 4.2.26 on 2025-12-24 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0047_category_abbreviation_category_colour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('system_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('system_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'schools',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campus',
            name='system_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.workpackage'),
        ),
        migrations.AlterField(
            model_name='assessmentresource',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.staff'),
        ),
        migrations.AlterField(
            model_name='assessmentstate',
            name='priority',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.campus'),
        ),
        migrations.AlterField(
            model_name='module',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.workpackage'),
        ),
        migrations.AlterField(
            model_name='module',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.modulesize'),
        ),
        migrations.AlterField(
            model_name='modulestaff',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.workpackage'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.workpackage'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
