# Generated by Django 4.2.26 on 2025-12-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0048_faculty_school_campus_system_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loads.faculty'),
        ),
    ]
