# Generated by Django 4.2.26 on 2025-12-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0049_school_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.campus'),
        ),
        migrations.AddField(
            model_name='staff',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.faculty'),
        ),
        migrations.AddField(
            model_name='staff',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.school'),
        ),
    ]
