# Generated by Django 4.2.26 on 2026-01-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0050_staff_campus_staff_faculty_staff_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresource',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.campus'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.faculty'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.school'),
        ),
    ]
