# Generated by Django 6.0.2 on 2026-05-07 13:31

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0051_alter_assessmentresource_details_alter_staff_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='semester',
            field=models.CharField(default='1.2,3', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='activitygenerator',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='The comment added to generated activities', max_length=200),
        ),
        migrations.AlterField(
            model_name='activitygenerator',
            name='details',
            field=models.TextField(help_text='Additional details of the generator itself'),
        ),
    ]
