# Generated by Django 6.0.2 on 2026-05-07 13:32

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0052_alter_activity_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='semester',
            field=models.CharField(default='1,2,3', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
