# Generated by Django 6.0.2 on 2026-08-14 12:37

import django.core.validators
import django.db.models.deletion
import loads.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0053_alter_activity_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='coordinator_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hours for Module Coordination. Leave blank for an estimate from an automated formula.', null=True),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='admin_formula',
            field=models.TextField(blank=True, default='contact * admin_scaling', help_text='Formula for admin hours. Variables: credits, students, contact, (deprecated: admin_scaling, assessment_scaling).', validators=[loads.validators.validate_formula]),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='assessment_formula',
            field=models.TextField(blank=True, default='contact * assessment_scaling', help_text='Formula for assessment hours. Variables: credits, students, contact, admin, (deprecated: admin_scaling, assessment_scaling).', validators=[loads.validators.validate_formula]),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='contact_formula',
            field=models.TextField(blank=True, default='credits * contact_scaling', help_text='Formula for contact hours. Variables: credits, students, (deprecated: contact_scaling).', validators=[loads.validators.validate_formula]),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='coordinator_activity_type',
            field=models.ForeignKey(blank=True, help_text='The activity type used to categorise coordinator hours.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.activitytype'),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='coordinator_formula',
            field=models.TextField(blank=True, default='15 + students * 0.01', help_text='Formula for coordinator admin hours. Variables: students, credits.', validators=[loads.validators.validate_formula]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(help_text='The activity type is used to help categorise this workload.', on_delete=django.db.models.deletion.CASCADE, to='loads.activitytype'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='Optionally, add any comment associated with this activity here.', max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Optionally, if this activity is associated with a module, enter it here.', null=True, on_delete=django.db.models.deletion.CASCADE, to='loads.module'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(help_text='Specify the name of the activity.', max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='If known, allocate this workload to a specific member of staff.', limit_choices_to={'is_external': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.staff'),
        ),
        migrations.AlterField(
            model_name='module',
            name='admin_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hours for other aspects of Admin. Leave blank for an estimate from an automated formula.', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='assessment_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hours for other aspects of Assessment. Leave blank for an estimate from an automated formula.', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='contact_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Contact Hours with Students. Leave blank for an estimate from an automated formula.', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='details',
            field=models.TextField(blank=True, help_text='Use this optional field for any explanatory comment.', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='lead_programme',
            field=models.ForeignKey(blank=True, help_text='The External Examiner(s) for this programme will be considered the lead examiner, for assessment purposes only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_modules', to='loads.programme'),
        ),
        migrations.AlterField(
            model_name='module',
            name='moderators',
            field=models.ManyToManyField(blank=True, help_text='Specify who should moderate any assessments in this module. For assessment purposes only.', limit_choices_to={'is_external': False}, related_name='moderated_modules', to='loads.staff'),
        ),
        migrations.AlterField(
            model_name='module',
            name='programmes',
            field=models.ManyToManyField(blank=True, help_text='Specify which programmes this module belongs to, for assessment purposes only.', related_name='modules', to='loads.programme'),
        ),
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.CharField(help_text='Specify which semester(s) this module runs in.', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.workpackage'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
