# Generated by Django 6.0.2 on 2026-08-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0055_add_number_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='number_students',
            field=models.PositiveSmallIntegerField(help_text='Number of students, or approximate number of students enrolled', verbose_name='Number of students'),
        ),
    ]
