# Generated by Django 6.0.2 on 2026-08-16 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0056_alter_module_number_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loads.modulesize'),
        ),
    ]
